name: pipeline
run-name: ${{ github.actor }} is creating his first pipeline
on: [push]
jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./run.sh
