name: pipeline
run-name: ${{ github.actor }} is creating his first pipeline
on: [push]
jobs:
  use-bash-shell-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sh ./run.sh
